{
    'name': 'Quality Control MTC SVCO',
    'version': '18.0.1.0.0',
    'category': 'Quality control',
    'summary': 'Mill Test Certificate',
    'website': 'https://www.github.com/safyric/safyric-odoo-addons',
    'depends': [
        'quality_control_oca',
        'sale',
        'sale_stock',
        'product',
    ],
    'data': [
        'security/ir.model.access.csv',
        'wizard/qc_mtc_add_heat_views.xml',
        'views/qc_mtc_views.xml',
        'views/qc_inspection_views.xml',
        'views/res_config_settings.xml',
        'views/product_attribute_views.xml',
        'report/qc_mtc_report.xml',
        'report/qc_mtc_report_layout.xml',
        'report/qc_mtc_report_template.xml',
    ],
    'installable': True,
    'license': 'LGPL-3',
}
